name: Monitor Superfinanciera

on:
  schedule:
    - cron: "0 13,19 * * *"  # 08:00 y 14:00 hora Colombia
  workflow_dispatch:

jobs:
  check_new_report:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run scraper
        id: scraping
        run: |
          python scrap_sup_ind.py
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

      - name: Commit changes if new month
        if: steps.scraping.outcome == 'failure' # exit code 1 triggers this
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ultimo_mes.txt
          git commit -m "Actualizar último mes detectado: $(cat ultimo_mes.txt)"
          git push
